# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEuropeanUpAndInCallPrice <- function(nInt, Strike, Spot, Vol, Rfr, Expiry, barrier, nReps = 1000L) {
    .Call(`_myoptionPricer2_getEuropeanUpAndInCallPrice`, nInt, Strike, Spot, Vol, Rfr, Expiry, barrier, nReps)
}

rcpp_hello <- function() {
    .Call(`_myoptionPricer2_rcpp_hello`)
}

